### ISSUE TITLE
Problem with the List Generation with TiddlyWiki

### ISSUE THREAD

**Issue by Sinister267** [Skeeve/TiddlyStuff#1]
Hello Skeeve,

I am currently working on a University Project and i found your showcase for the small Contacs DB and i tried to recreate it on the current TiddlyWiki version and i got some Problems with the generation of the Tables. 
![TiddlyWiki_Problem](https://user-images.githubusercontent.com/40772496/56726016-40930e00-674e-11e9-8eaa-a89e54900534.png)

[MyFirstTiddlyWiki.zip](https://github.com/Skeeve/TiddlyStuff/files/3116240/MyFirstTiddlyWiki.zip)

Here u can see my Code aswell.

Could you maybe help me what I could do to make it work on the current version

Thank you in advance

Artur 

ps. you can also answer in german :D

**Comment by Skeeve** [comment]
Hallo Artur.

Ist das Problem nur, dass die Wiki-Tabelle nicht als Tabelle rauskommt?

Dann ist die Lösung einfach: Nimm eine HTML Tabelle.

```html
<table>
<tr><th>Context          </th><td><$edit field="context"/>          </td></tr>
<tr><th>Example          </th><td><$edit field="example"/>          </td></tr>
<tr><th>Forces           </th><td><$edit field="forces"/>           </td></tr>
<tr><th>Problem          </th><td><$edit field="problem"/>          </td></tr>
<tr><th>Related Patterns </th><td><$edit field="related_patterns"/> </td></tr>
<tr><th>Result           </th><td><$edit field="result"/>           </td></tr>
<tr><th>Solution         </th><td><$edit field="solution"/>         </td></tr>
</table>
```

**Comment by Sinister267** [comment]
Hallo Stephan,




Danke für die super schnelle Antwort :). Das zum einen zum anderen werden die Felder die ich im Skeleton habe nicht angezeigt werden sondern als [! Conext |.. 




Artur 






On Thu, Apr 25, 2019 at 11:48 AM +0200, "Stephan Hradek" <notifications@github.com> wrote:












Hallo Artur.



Ist das Problem nur, dass die Wiki-Tabelle nicht als Tabelle rauskommt?



Dann ist die Lösung einfach: Nimm eine HTML Tabelle.

<table>

<tr><th>Context          </th><td><$edit field="context"/>          </td></tr>

<tr><th>Example          </th><td><$edit field="example"/>          </td></tr>

<tr><th>Forces           </th><td><$edit field="forces"/>           </td></tr>

<tr><th>Problem          </th><td><$edit field="problem"/>          </td></tr>

<tr><th>Related Patterns </th><td><$edit field="related_patterns"/> </td></tr>

<tr><th>Result           </th><td><$edit field="result"/>           </td></tr>

<tr><th>Solution         </th><td><$edit field="solution"/>         </td></tr>

</table>

**Comment by Sinister267** [comment]
Zu schnell gedrückt. Es wird quasi als markup angezeigt. Danke für deine Hilfe und viele Grüße Artur  






On Thu, Apr 25, 2019 at 11:48 AM +0200, "Stephan Hradek" <notifications@github.com> wrote:












Hallo Artur.



Ist das Problem nur, dass die Wiki-Tabelle nicht als Tabelle rauskommt?



Dann ist die Lösung einfach: Nimm eine HTML Tabelle.

<table>

<tr><th>Context          </th><td><$edit field="context"/>          </td></tr>

<tr><th>Example          </th><td><$edit field="example"/>          </td></tr>

<tr><th>Forces           </th><td><$edit field="forces"/>           </td></tr>

<tr><th>Problem          </th><td><$edit field="problem"/>          </td></tr>

<tr><th>Related Patterns </th><td><$edit field="related_patterns"/> </td></tr>

<tr><th>Result           </th><td><$edit field="result"/>           </td></tr>

<tr><th>Solution         </th><td><$edit field="solution"/>         </td></tr>

</table>

**Comment by Skeeve** [comment]
Tut mir leid, aber ich kann dem nicht folgen.

Beschreib mal, wie Du Dir das ganze gedacht hast. Vielleicht verstehe ich es dann.

**Comment by Sinister267** [comment]
Hallo Stephan,

Danke für deine Hilfe es hat alles super funktioniert :). Sorry habe letztes mal vergessen mich direkt zu bedanken.

Wollte fragen ob du vielleicht wüsstest ob es eine Möglichkeit gäbe die Felder in denen ich die Sachen eintrage zu "Textareas" machen kann?

Danke im voraus und viele Grüße
Artur

**Comment by Skeeve** [comment]
Hi Artur.

Du meinst ein [$edit-text](https://tiddlywiki.com/#EditTextWidget)?

**Comment by Sinister267** [comment]
Hi Stephan,

nein ich meine das Ziel des $edit-text. Ich möchte im Prinzip ganze Paragraphen dort formatiert einfügen.
Ich habe mir schon überlegt ob ich nicht einfach die "New Journal" Funktion umbauen kann
